name: Über mich
favicon: null
layout_spectrum: 0.8036837973631918
typography_spectrum: 0.8234600585419685
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2321040192618966
  lightness: 0.4192223008722067
  saturation: 0.47124679386615753
  rhythmicContrast: 0.03392370347864926
purpose: []
